// ============================================================
// MAVEK BCS — Static site data (industries, solutions, insights)
// ============================================================

export const INDUSTRIES = [
  { slug: "automotive", name: "Automotive", nameKo: "자동차", nameJa: "自動車", icon: "🚗",
    description: "Supporting automotive OEMs and suppliers with financial close, planning, and supply chain finance solutions for a rapidly transforming industry.",
    descriptionKo: "빠르게 변화하는 산업을 위한 재무 결산, 계획 및 공급망 재무 솔루션으로 자동차 OEM 및 공급업체를 지원합니다.",
    descriptionJa: "急速に変化する業界向けの財務決算、計画、サプライチェーン財務ソリューションで自動車OEMとサプライヤーをサポートします。" },
  { slug: "semiconductors", name: "Semiconductors", nameKo: "반도체", nameJa: "半導体", icon: "💡",
    description: "Managing complex R&D cost allocation, IP licensing, and demand volatility with advanced financial analytics and planning tools.",
    descriptionKo: "고급 재무 분석 및 계획 도구로 복잡한 R&D 비용 배분, IP 라이선싱 및 수요 변동성을 관리합니다.",
    descriptionJa: "高度な財務分析・計画ツールで複雑なR&Dコスト配分、IPライセンス、需要変動を管理します。" },
  { slug: "pharmaceuticals", name: "Pharmaceuticals", nameKo: "제약", nameJa: "製薬", icon: "💊",
    description: "Navigating long product development cycles, complex royalty structures, and stringent regulatory reporting requirements in the life sciences sector.",
    descriptionKo: "생명과학 분야에서 긴 제품 개발 주기, 복잡한 로열티 구조 및 엄격한 규제 보고 요건을 처리합니다.",
    descriptionJa: "ライフサイエンス分野で長い製品開発サイクル、複雑なロイヤルティ構造、厳格な規制報告要件に対応します。" },
  { slug: "telecommunications", name: "Telecommunications", nameKo: "통신", nameJa: "通信", icon: "📡",
    description: "Handling complex billing arrangements, network infrastructure investments, and multi-market regulatory compliance for telecom operators.",
    descriptionKo: "통신 사업자를 위한 복잡한 청구 계약, 네트워크 인프라 투자 및 다중 시장 규제 준수를 처리합니다.",
    descriptionJa: "通信事業者向けの複雑な請求契約、ネットワークインフラ投資、マルチマーケット規制コンプライアンスに対応します。" },
  { slug: "oil-and-gas", name: "Oil & Gas", nameKo: "석유 및 가스", nameJa: "石油・ガス", icon: "⛽",
    description: "Managing commodity price risk, joint venture accounting, and complex project finance for upstream, midstream, and downstream operations.",
    descriptionKo: "상류, 중류 및 하류 운영을 위한 원자재 가격 위험, 합작 투자 회계 및 복잡한 프로젝트 재무를 관리합니다.",
    descriptionJa: "上流、中流、下流の操業における商品価格リスク、ジョイントベンチャー会計、複雑なプロジェクト財務を管理します。" },
  { slug: "renewable-energy", name: "Renewable Energy", nameKo: "재생 에너지", nameJa: "再生可能エネルギー", icon: "🌱",
    description: "Supporting the energy transition with financial solutions for project finance, ESG reporting, and asset lifecycle management in renewable energy.",
    descriptionKo: "재생 에너지의 프로젝트 재무, ESG 보고 및 자산 수명 주기 관리를 위한 재무 솔루션으로 에너지 전환을 지원합니다.",
    descriptionJa: "再生可能エネルギーのプロジェクト財務、ESGレポーティング、資産ライフサイクル管理のための財務ソリューションでエネルギー転換をサポートします。" },
  { slug: "financial-services", name: "Financial Services", nameKo: "금융 서비스", nameJa: "金融サービス", icon: "🏦",
    description: "Delivering financial close, regulatory reporting, and risk management solutions for banks, insurers, and asset managers operating in complex regulatory environments.",
    descriptionKo: "복잡한 규제 환경에서 운영되는 은행, 보험사 및 자산 관리자를 위한 재무 결산, 규제 보고 및 위험 관리 솔루션을 제공합니다.",
    descriptionJa: "複雑な規制環境で運営される銀行、保険会社、資産管理会社向けの財務決算、規制報告、リスク管理ソリューションを提供します。" },
  { slug: "real-estate", name: "Real Estate", nameKo: "부동산", nameJa: "不動産", icon: "🏢",
    description: "Managing complex lease portfolios, property valuations, and IFRS 16 compliance for real estate companies and property investors.",
    descriptionKo: "부동산 회사 및 부동산 투자자를 위한 복잡한 리스 포트폴리오, 부동산 평가 및 IFRS 16 준수를 관리합니다.",
    descriptionJa: "不動産会社と不動産投資家向けの複雑なリースポートフォリオ、不動産評価、IFRS 16コンプライアンスを管理します。" },
  { slug: "retail", name: "Retail", nameKo: "소매", nameJa: "小売", icon: "🛍️",
    description: "Enabling retail and e-commerce organizations to manage high transaction volumes, multi-jurisdiction tax compliance, and real-time financial visibility.",
    descriptionKo: "소매 및 이커머스 조직이 높은 거래량, 다중 관할 세금 준수 및 실시간 재무 가시성을 관리할 수 있도록 지원합니다.",
    descriptionJa: "小売・Eコマース組織が高い取引量、複数管轄の税務コンプライアンス、リアルタイムの財務可視性を管理できるよう支援します。" },
  { slug: "energy", name: "Energy", nameKo: "에너지", nameJa: "エネルギー", icon: "⚡",
    description: "Supporting energy companies with commodity risk management, capital project finance, and regulatory compliance across the energy value chain.",
    descriptionKo: "에너지 가치 사슬 전반에 걸쳐 원자재 위험 관리, 자본 프로젝트 재무 및 규제 준수로 에너지 기업을 지원합니다.",
    descriptionJa: "エネルギーバリューチェーン全体で商品リスク管理、資本プロジェクト財務、規制コンプライアンスでエネルギー企業をサポートします。" },
  { slug: "utilities", name: "Utilities", nameKo: "공공 서비스", nameJa: "公益事業", icon: "🔧",
    description: "Addressing the unique financial management needs of utility companies including regulated asset base management, tariff modeling, and infrastructure investment planning.",
    descriptionKo: "규제 자산 기반 관리, 요금 모델링 및 인프라 투자 계획을 포함한 공공 서비스 기업의 고유한 재무 관리 요구를 해결합니다.",
    descriptionJa: "規制資産ベース管理、料金モデリング、インフラ投資計画を含む公益事業会社の固有の財務管理ニーズに対応します。" },
  { slug: "electronics-manufacturing", name: "Electronics Manufacturing", nameKo: "전자 제조", nameJa: "電子機器製造", icon: "🖥️",
    description: "Managing complex global supply chains, product cost accounting, and warranty provisions for electronics manufacturers operating in competitive markets.",
    descriptionKo: "경쟁 시장에서 운영되는 전자 제조업체를 위한 복잡한 글로벌 공급망, 제품 원가 회계 및 보증 충당금을 관리합니다.",
    descriptionJa: "競争市場で運営される電子機器メーカー向けの複雑なグローバルサプライチェーン、製品原価会計、保証引当金を管理します。" }
      ];

export const SOLUTION_CATEGORIES = [
  {
    slug: "closing",
    name: "Closing",
    nameKo: "결산",
    nameJa: "決算",
    icon: "CheckSquare",
    description: "Streamline financial close processes with automated reconciliation, consolidation, and reporting.",
    descriptionKo: "자동화된 조정, 연결 및 보고를 통해 재무 결산 프로세스를 간소화합니다.",
    descriptionJa: "自動化された照合、連結、レポートで財務決算プロセスを効率化します。",
    solutions: [
      {
        slug: "sap-afc",
        name: "SAP Advanced Financial Closing (AFC)",
        nameKo: "SAP 고급 재무 결산 (AFC)",
        nameJa: "SAP アドバンスト財務決算 (AFC)",
        vendor: "SAP",
        youtubeVideoId: "AnIJ6iGA-f4",
        shortDescription: "Automate and accelerate your financial close with SAP's intelligent closing solution.",
        shortDescriptionKo: "SAP의 지능형 결산 솔루션으로 재무 결산을 자동화하고 가속화합니다.",
        shortDescriptionJa: "SAPのインテリジェントな決算ソリューションで財務決算を自動化・加速します。",
      },
      {
        slug: "sap-group-reporting",
        name: "SAP Group Reporting",
        nameKo: "SAP 그룹 보고",
        nameJa: "SAP グループレポーティング",
        vendor: "SAP",
        youtubeVideoId: "BznGGL3Jklo",
        shortDescription: "Consolidate financial data across your entire enterprise with real-time group reporting.",
        shortDescriptionKo: "실시간 그룹 보고로 전체 기업의 재무 데이터를 통합합니다.",
        shortDescriptionJa: "リアルタイムのグループレポーティングで企業全体の財務データを統合します。",
      },
      {
        slug: "oracle-fccs",
        name: "Oracle Financial Consolidation and Close Cloud Service (FCCS)",
        nameKo: "Oracle 재무 통합 및 결산 클라우드 서비스 (FCCS)",
        nameJa: "Oracle 財務連結・決算クラウドサービス (FCCS)",
        vendor: "Oracle",
        youtubeVideoId: "tn7VosL4yJY",
        shortDescription: "Cloud-based financial consolidation and close solution for complex multi-entity organizations.",
        shortDescriptionKo: "복잡한 다중 법인 조직을 위한 클라우드 기반 재무 통합 및 결산 솔루션.",
        shortDescriptionJa: "複雑なマルチエンティティ組織向けのクラウドベースの財務連結・決算ソリューション。",
      },
      {
        slug: "oracle-arcs",
        name: "Oracle Account Reconciliation Cloud Service (ARCS)",
        nameKo: "Oracle 계정 조정 클라우드 서비스 (ARCS)",
        nameJa: "Oracle アカウント調整クラウドサービス (ARCS)",
        vendor: "Oracle",
        youtubeVideoId: "YADE7ST-vDw",
        shortDescription: "Automate account reconciliations and reduce risk with Oracle's cloud reconciliation platform.",
        shortDescriptionKo: "Oracle의 클라우드 조정 플랫폼으로 계정 조정을 자동화하고 위험을 줄입니다.",
        shortDescriptionJa: "Oracleのクラウド調整プラットフォームでアカウント調整を自動化し、リスクを軽減します。",
      },
      {
        slug: "blackline",
        name: "Blackline",
        nameKo: "블랙라인",
        nameJa: "ブラックライン",
        vendor: "Blackline",
        youtubeVideoId: "lta7NJYiOYU",
        shortDescription: "Modern accounting platform that automates and controls the financial close process.",
        shortDescriptionKo: "재무 결산 프로세스를 자동화하고 제어하는 현대적인 회계 플랫폼.",
        shortDescriptionJa: "財務決算プロセスを自動化・制御する最新の会計プラットフォーム。",
      }
      ],
  },
  {
    slug: "tax",
    name: "Tax",
    nameKo: "세금",
    nameJa: "税務",
    icon: "FileText",
    description: "Ensure global tax compliance and automate document reporting with SAP's tax management solutions.",
    descriptionKo: "SAP의 세금 관리 솔루션으로 글로벌 세금 준수를 보장하고 문서 보고를 자동화합니다.",
    descriptionJa: "SAPの税務管理ソリューションでグローバルな税務コンプライアンスを確保し、文書レポートを自動化します。",
    solutions: [
      {
        slug: "sap-drc",
        name: "SAP Document and Reporting Compliance (DRC)",
        nameKo: "SAP 문서 및 보고 규정 준수 (DRC)",
        nameJa: "SAP ドキュメント・レポーティングコンプライアンス (DRC)",
        vendor: "SAP",
        youtubeVideoId: "H_b43fCqfUE",
        shortDescription: "Achieve global e-invoicing and tax reporting compliance with SAP DRC.",
        shortDescriptionKo: "SAP DRC로 글로벌 전자 인보이스 및 세금 보고 규정 준수를 달성합니다.",
        shortDescriptionJa: "SAP DRCでグローバルな電子請求書と税務報告のコンプライアンスを達成します。",
      }
      ],
  },
  {
    slug: "treasury",
    name: "Treasury",
    nameKo: "재무",
    nameJa: "トレジャリー",
    icon: "TrendingUp",
    description: "Optimize cash management, risk management, and banking connectivity with SAP Treasury solutions.",
    descriptionKo: "SAP 재무 솔루션으로 현금 관리, 위험 관리 및 은행 연결을 최적화합니다.",
    descriptionJa: "SAPトレジャリーソリューションで現金管理、リスク管理、銀行接続を最適化します。",
    solutions: [
      {
        slug: "sap-trm",
        name: "SAP Treasury and Risk Management (TRM)",
        nameKo: "SAP 재무 및 위험 관리 (TRM)",
        nameJa: "SAP トレジャリー・リスク管理 (TRM)",
        vendor: "SAP",
        youtubeVideoId: "Efl3DAU78OI",
        shortDescription: "Comprehensive treasury and risk management for financial instruments and hedging strategies.",
        shortDescriptionKo: "금융 상품 및 헤징 전략을 위한 포괄적인 재무 및 위험 관리.",
        shortDescriptionJa: "金融商品とヘッジ戦略のための包括的なトレジャリー・リスク管理。",
      },
      {
        slug: "sap-cash-management",
        name: "SAP Cash Management",
        nameKo: "SAP 현금 관리",
        nameJa: "SAP キャッシュマネジメント",
        vendor: "SAP",
        youtubeVideoId: "mq2uGLTy78M",
        shortDescription: "Real-time cash visibility and liquidity management across your global banking landscape.",
        shortDescriptionKo: "글로벌 은행 환경 전반에 걸쳐 실시간 현금 가시성 및 유동성 관리.",
        shortDescriptionJa: "グローバルな銀行環境全体でのリアルタイムの現金可視性と流動性管理。",
      },
      {
        slug: "sap-mbc",
        name: "SAP Multi-Bank Connectivity (MBC)",
        nameKo: "SAP 멀티 뱅크 연결 (MBC)",
        nameJa: "SAP マルチバンクコネクティビティ (MBC)",
        vendor: "SAP",
        youtubeVideoId: "Er5rkkfvb4s",
        shortDescription: "Connect to multiple banks through a single, standardized interface for payment processing.",
        shortDescriptionKo: "단일 표준화된 인터페이스를 통해 여러 은행에 연결하여 결제를 처리합니다.",
        shortDescriptionJa: "単一の標準化されたインターフェースを通じて複数の銀行に接続し、支払いを処理します。",
      }
      ],
  },
  {
    slug: "financial-supply-chain",
    name: "Financial Supply Chain",
    nameKo: "재무 공급망",
    nameJa: "財務サプライチェーン",
    icon: "Link",
    description: "Optimize credit, collections, and dispute management across your financial supply chain.",
    descriptionKo: "재무 공급망 전반에 걸쳐 신용, 수금 및 분쟁 관리를 최적화합니다.",
    descriptionJa: "財務サプライチェーン全体でクレジット、回収、紛争管理を最適化します。",
    solutions: [
      {
        slug: "sap-fscm",
        name: "SAP Financial Supply Chain Management (Credit, Collection, Dispute)",
        nameKo: "SAP 재무 공급망 관리 (신용, 수금, 분쟁)",
        nameJa: "SAP 財務サプライチェーン管理 (クレジット、回収、紛争)",
        vendor: "SAP",
        youtubeVideoId: "ltSYmaYxC-M",
        shortDescription: "End-to-end financial supply chain management covering credit, collections, and dispute resolution.",
        shortDescriptionKo: "신용, 수금 및 분쟁 해결을 포함하는 엔드투엔드 재무 공급망 관리.",
        shortDescriptionJa: "クレジット、回収、紛争解決をカバーするエンドツーエンドの財務サプライチェーン管理。",
      }
      ],
  },
  {
    slug: "billing",
    name: "Billing",
    nameKo: "청구",
    nameJa: "請求",
    icon: "Receipt",
    description: "Transform billing and revenue management with SAP's comprehensive BRIM solution.",
    descriptionKo: "SAP의 포괄적인 BRIM 솔루션으로 청구 및 수익 관리를 혁신합니다.",
    descriptionJa: "SAPの包括的なBRIMソリューションで請求・収益管理を変革します。",
    solutions: [
      {
        slug: "sap-brim",
        name: "SAP Billing and Revenue Innovation Management (BRIM)",
        nameKo: "SAP 청구 및 수익 혁신 관리 (BRIM)",
        nameJa: "SAP 請求・収益イノベーション管理 (BRIM)",
        vendor: "SAP",
        youtubeVideoId: "QZewVO1pqqs",
        shortDescription: "Flexible billing and revenue management for subscription, usage-based, and hybrid business models.",
        shortDescriptionKo: "구독, 사용 기반 및 하이브리드 비즈니스 모델을 위한 유연한 청구 및 수익 관리.",
        shortDescriptionJa: "サブスクリプション、使用量ベース、ハイブリッドビジネスモデルのための柔軟な請求・収益管理。",
      }
      ],
  },
  {
    slug: "risk",
    name: "Risk",
    nameKo: "위험",
    nameJa: "リスク",
    icon: "Shield",
    description: "Manage governance, risk, and compliance across your enterprise with SAP GRC.",
    descriptionKo: "SAP GRC로 기업 전반의 거버넌스, 위험 및 규정 준수를 관리합니다.",
    descriptionJa: "SAP GRCで企業全体のガバナンス、リスク、コンプライアンスを管理します。",
    solutions: [
      {
        slug: "sap-grc",
        name: "SAP Governance, Risk and Compliance (GRC)",
        nameKo: "SAP 거버넌스, 위험 및 규정 준수 (GRC)",
        nameJa: "SAP ガバナンス・リスク・コンプライアンス (GRC)",
        vendor: "SAP",
        youtubeVideoId: "_qK1mEx0tNU",
        shortDescription: "Integrated governance, risk, and compliance management to protect your enterprise.",
        shortDescriptionKo: "기업을 보호하기 위한 통합 거버넌스, 위험 및 규정 준수 관리.",
        shortDescriptionJa: "企業を守るための統合ガバナンス・リスク・コンプライアンス管理。",
      }
      ],
  },
  {
    slug: "planning",
    name: "Planning",
    nameKo: "계획",
    nameJa: "計画",
    icon: "BarChart2",
    description: "Drive intelligent planning and budgeting with SAP Analytics Cloud and Oracle PBCS.",
    descriptionKo: "SAP Analytics Cloud 및 Oracle PBCS로 지능형 계획 및 예산 책정을 추진합니다.",
    descriptionJa: "SAP Analytics CloudとOracle PBCSでインテリジェントな計画・予算策定を推進します。",
    solutions: [
      {
        slug: "sap-analytics-cloud",
        name: "SAP Analytics Cloud (SAC)",
        nameKo: "SAP 애널리틱스 클라우드 (SAC)",
        nameJa: "SAP アナリティクスクラウド (SAC)",
        vendor: "SAP",
        youtubeVideoId: "YuzvTrSpWVo",
        shortDescription: "Unified analytics, planning, and predictive capabilities in a single cloud solution.",
        shortDescriptionKo: "단일 클라우드 솔루션에서 통합 분석, 계획 및 예측 기능.",
        shortDescriptionJa: "単一のクラウドソリューションで統合分析、計画、予測機能を提供。",
      },
      {
        slug: "oracle-pbcs",
        name: "Oracle Planning and Budgeting Cloud Service (PBCS)",
        nameKo: "Oracle 계획 및 예산 클라우드 서비스 (PBCS)",
        nameJa: "Oracle 計画・予算クラウドサービス (PBCS)",
        vendor: "Oracle",
        youtubeVideoId: "mKyrdpTq1UY",
        shortDescription: "Cloud-based planning and budgeting solution for agile financial planning.",
        shortDescriptionKo: "민첩한 재무 계획을 위한 클라우드 기반 계획 및 예산 솔루션.",
        shortDescriptionJa: "アジャイルな財務計画のためのクラウドベースの計画・予算ソリューション。",
      }
      ],
  },
  {
    slug: "lease",
    name: "Lease",
    nameKo: "리스",
    nameJa: "リース",
    icon: "Building",
    description: "Manage real estate and lease accounting compliance with SAP RE-FX.",
    descriptionKo: "SAP RE-FX로 부동산 및 리스 회계 규정 준수를 관리합니다.",
    descriptionJa: "SAP RE-FXで不動産とリース会計のコンプライアンスを管理します。",
    solutions: [
      {
        slug: "sap-re-fx",
        name: "SAP Real Estate Management (RE-FX)",
        nameKo: "SAP 부동산 관리 (RE-FX)",
        nameJa: "SAP 不動産管理 (RE-FX)",
        vendor: "SAP",
        youtubeVideoId: "5tGzf2Kd5wo",
        shortDescription: "Comprehensive real estate and lease management with IFRS 16 compliance built in.",
        shortDescriptionKo: "IFRS 16 준수가 내장된 포괄적인 부동산 및 리스 관리.",
        shortDescriptionJa: "IFRS 16コンプライアンスを内蔵した包括的な不動産・リース管理。",
      }
      ],
  }
      ];

export const INSIGHT_CATEGORIES = [
  "Financial Close",
  "Planning & Budgeting",
  "Tax & Compliance",
  "Treasury",
  "Financial Supply Chain",
  "Billing & Revenue",
  "Risk & Compliance",
  "Lease Management",
  "Finance Transformation",
  "Industry Trends",
  "Technology",
  "Industry Focus"
      ];

export const INSIGHTS: Array<{
  slug: string;
  title: string;
  titleKo: string;
  titleJa: string;
  excerpt: string;
  excerptKo?: string;
  excerptJa?: string;
  category: string;
  tags: string[];
  relatedIndustries: string[];
  relatedSolutions: string[];
  readTimeMinutes: number;
  featured: boolean;
}> = [
  // Financial Close (6)
  {
    slug: "what-is-advanced-financial-closing-afc",
    title: "What is Advanced Financial Closing (AFC)?",
    titleKo: "고급 재무 결산(AFC)이란 무엇인가?",
    titleJa: "アドバンスト財務決算(AFC)とは何か？",
    excerpt: "SAP Advanced Financial Closing (AFC) is an intelligent solution that automates and accelerates the financial close process, reducing manual effort and improving accuracy.",
    excerptKo: "SAP AFC(고급 재무 결산)는 재무 결산 프로세스를 자동화하고 가속화하는 지능형 솔루션으로, 수작업을 줄이고 정확성을 향상시킵니다.",
    excerptJa: "SAP AFC（アドバンスト財務決算）は、財務決算プロセスを自動化・加速するインテリジェントなソリューションで、手作業を削減し精度を向上させます。",
    category: "Financial Close",
    tags: ["SAP AFC", "Financial Close", "Automation"],
    relatedIndustries: ["financial-services", "retail", "automotive"],
    relatedSolutions: ["sap-afc"],
    readTimeMinutes: 7,
    featured: true,
  },
  {
    slug: "group-reporting-explained",
    title: "Group Reporting Explained",
    titleKo: "그룹 보고 설명",
    titleJa: "グループレポーティング解説",
    excerpt: "SAP Group Reporting enables real-time financial consolidation and reporting across complex corporate structures, replacing legacy consolidation tools.",
    category: "Financial Close",
    tags: ["SAP Group Reporting", "Consolidation", "Financial Close"],
    relatedIndustries: ["financial-services", "pharmaceuticals", "telecommunications"],
    relatedSolutions: ["sap-group-reporting"],
    readTimeMinutes: 6,
    featured: false,
  },
  {
    slug: "why-financial-close-is-still-broken",
    title: "Why Financial Close is Still Broken",
    titleKo: "재무 결산이 여전히 문제인 이유",
    titleJa: "なぜ財務決算はまだ問題なのか",
    excerpt: "Despite decades of ERP investment, most finance teams still struggle with manual reconciliations, spreadsheet dependencies, and missed deadlines during the close cycle.",
    category: "Financial Close",
    tags: ["Financial Close", "Finance Transformation", "ERP"],
    relatedIndustries: ["financial-services", "retail", "energy"],
    relatedSolutions: ["sap-afc", "blackline"],
    readTimeMinutes: 8,
    featured: false,
  },
  {
    slug: "blackline-vs-erp-close-tools",
    title: "BlackLine vs ERP Close Tools",
    titleKo: "블랙라인 vs ERP 결산 도구",
    titleJa: "ブラックラインvsERPクローズツール",
    excerpt: "A detailed comparison of BlackLine's best-of-breed approach versus native ERP financial close tools, examining capabilities, implementation complexity, and total cost of ownership.",
    category: "Financial Close",
    tags: ["Blackline", "ERP", "Financial Close", "Best-of-Breed"],
    relatedIndustries: ["financial-services", "pharmaceuticals"],
    relatedSolutions: ["blackline", "sap-afc"],
    readTimeMinutes: 9,
    featured: false,
  },
  {
    slug: "oracle-fccs-for-complex-consolidations",
    title: "Oracle FCCS for Complex Consolidations",
    titleKo: "복잡한 연결을 위한 Oracle FCCS",
    titleJa: "複雑な連結のためのOracle FCCS",
    excerpt: "Oracle Financial Consolidation and Close Cloud Service (FCCS) provides a powerful platform for organizations with complex multi-entity, multi-currency consolidation requirements.",
    category: "Financial Close",
    tags: ["Oracle FCCS", "Consolidation", "Cloud"],
    relatedIndustries: ["financial-services", "real-estate", "retail"],
    relatedSolutions: ["oracle-fccs"],
    readTimeMinutes: 7,
    featured: false,
  },
  {
    slug: "account-reconciliation-best-practices",
    title: "Account Reconciliation Best Practices",
    titleKo: "계정 조정 모범 사례",
    titleJa: "アカウント調整のベストプラクティス",
    excerpt: "Effective account reconciliation is the foundation of a reliable financial close. This guide covers automation strategies, risk-based prioritization, and continuous monitoring.",
    category: "Financial Close",
    tags: ["Account Reconciliation", "Oracle ARCS", "Automation"],
    relatedIndustries: ["financial-services", "retail"],
    relatedSolutions: ["oracle-arcs", "blackline"],
    readTimeMinutes: 8,
    featured: false,
  },
  // Planning & Budgeting (3)
  {
    slug: "continuous-planning-vs-traditional-budgeting",
    title: "Continuous Planning vs Traditional Budgeting",
    titleKo: "지속적 계획 vs 전통적 예산 책정",
    titleJa: "継続的計画vs従来の予算策定",
    excerpt: "The annual budget cycle is increasingly inadequate in a volatile business environment. Continuous planning offers a more agile, data-driven alternative.",
    category: "Planning & Budgeting",
    tags: ["Planning", "Budgeting", "Finance Transformation"],
    relatedIndustries: ["financial-services", "retail", "telecommunications"],
    relatedSolutions: ["sap-analytics-cloud", "oracle-pbcs"],
    readTimeMinutes: 7,
    featured: false,
  },
  {
    slug: "sap-analytics-cloud-for-planning",
    title: "SAP Analytics Cloud for Planning",
    titleKo: "계획을 위한 SAP 애널리틱스 클라우드",
    titleJa: "計画のためのSAP アナリティクスクラウド",
    excerpt: "SAP Analytics Cloud (SAC) combines business intelligence, planning, and predictive analytics in a single cloud platform, enabling finance teams to plan with greater speed and accuracy.",
    category: "Planning & Budgeting",
    tags: ["SAP Analytics Cloud", "Planning", "BI"],
    relatedIndustries: ["automotive", "semiconductors", "retail"],
    relatedSolutions: ["sap-analytics-cloud"],
    readTimeMinutes: 6,
    featured: false,
  },
  {
    slug: "why-excel-based-planning-fails",
    title: "Why Excel-Based Planning Fails",
    titleKo: "엑셀 기반 계획이 실패하는 이유",
    titleJa: "Excelベースの計画が失敗する理由",
    excerpt: "Spreadsheet-based planning creates version control nightmares, limits collaboration, and introduces significant error risk. Here's why organizations are moving to dedicated planning platforms.",
    category: "Planning & Budgeting",
    tags: ["Planning", "Excel", "Finance Transformation"],
    relatedIndustries: ["retail", "financial-services", "pharmaceuticals"],
    relatedSolutions: ["sap-analytics-cloud", "oracle-pbcs"],
    readTimeMinutes: 5,
    featured: false,
  },
  {
    slug: "driver-based-planning-explained",
    title: "Driver-Based Planning Explained",
    titleKo: "드라이버 기반 계획 설명",
    titleJa: "ドライバーベース計画の解説",
    excerpt: "Driver-based planning links financial outcomes to operational metrics, enabling more accurate forecasts and faster scenario modeling.",
    category: "Planning & Budgeting",
    tags: ["Planning", "Forecasting", "Driver-Based"],
    relatedIndustries: ["automotive", "retail", "telecommunications"],
    relatedSolutions: ["sap-analytics-cloud", "oracle-pbcs"],
    readTimeMinutes: 6,
    featured: false,
  },
  // Tax & Compliance (3)
  {
    slug: "what-is-drc-sap",
    title: "What is DRC (SAP)?",
    titleKo: "SAP DRC란 무엇인가?",
    titleJa: "SAP DRCとは何か？",
    excerpt: "SAP Document and Reporting Compliance (DRC) is SAP's solution for managing global e-invoicing mandates and tax reporting requirements across 60+ countries.",
    category: "Tax & Compliance",
    tags: ["SAP DRC", "Tax Compliance", "E-Invoicing"],
    relatedIndustries: ["retail", "automotive", "pharmaceuticals"],
    relatedSolutions: ["sap-drc"],
    readTimeMinutes: 7,
    featured: false,
  },
  {
    slug: "global-e-invoicing-trends",
    title: "Global E-Invoicing Trends",
    titleKo: "글로벌 전자 인보이스 트렌드",
    titleJa: "グローバル電子請求書トレンド",
    excerpt: "Governments worldwide are mandating real-time e-invoicing and digital tax reporting. Understanding these trends is critical for multinational organizations.",
    excerptKo: "전 세계 정부가 실시간 전자 인보이스 및 디지털 세금 신고를 의무화하고 있습니다. 다국적 기업에게 이러한 트렌드를 이해하는 것은 매우 중요합니다.",
    excerptJa: "世界中の政府がリアルタイムの電子請求書とデジタル税務申告を義務化しています。多国籍企業にとって、これらのトレンドを理解することは非常に重要です。",
    category: "Tax & Compliance",
    tags: ["E-Invoicing", "Tax Compliance", "Regulation"],
    relatedIndustries: ["retail", "automotive", "oil-and-gas"],
    relatedSolutions: ["sap-drc"],
    readTimeMinutes: 8,
    featured: true,
  },
  {
    slug: "tax-compliance-automation",
    title: "Tax Compliance Automation",
    titleKo: "세금 규정 준수 자동화",
    titleJa: "税務コンプライアンスの自動化",
    excerpt: "Automating tax compliance processes reduces manual effort, improves accuracy, and ensures timely reporting across multiple jurisdictions.",
    category: "Tax & Compliance",
    tags: ["Tax Compliance", "Automation", "SAP DRC"],
    relatedIndustries: ["financial-services", "retail", "telecommunications"],
    relatedSolutions: ["sap-drc"],
    readTimeMinutes: 6,
    featured: false,
  },
  // Treasury (3)
  {
    slug: "treasury-and-risk-management-trm",
    title: "Treasury and Risk Management (TRM)",
    titleKo: "재무 및 위험 관리 (TRM)",
    titleJa: "トレジャリー・リスク管理 (TRM)",
    excerpt: "SAP Treasury and Risk Management (TRM) provides comprehensive tools for managing financial instruments, hedging strategies, and treasury risk.",
    category: "Treasury",
    tags: ["SAP TRM", "Treasury", "Risk Management"],
    relatedIndustries: ["financial-services", "oil-and-gas", "utilities"],
    relatedSolutions: ["sap-trm"],
    readTimeMinutes: 7,
    featured: false,
  },
  {
    slug: "importance-of-cash-visibility",
    title: "Importance of Cash Visibility",
    titleKo: "현금 가시성의 중요성",
    titleJa: "現金可視性の重要性",
    excerpt: "Real-time cash visibility is a strategic imperative for CFOs. Without it, organizations face liquidity risk, missed investment opportunities, and inefficient capital allocation.",
    category: "Treasury",
    tags: ["Cash Management", "Treasury", "Liquidity"],
    relatedIndustries: ["financial-services", "retail", "energy"],
    relatedSolutions: ["sap-cash-management"],
    readTimeMinutes: 6,
    featured: false,
  },
  {
    slug: "multi-bank-connectivity-mbc",
    title: "Multi-Bank Connectivity (MBC)",
    titleKo: "멀티 뱅크 연결 (MBC)",
    titleJa: "マルチバンクコネクティビティ (MBC)",
    excerpt: "SAP Multi-Bank Connectivity (MBC) simplifies bank communication by providing a single, standardized channel for payment processing and bank statement retrieval.",
    category: "Treasury",
    tags: ["SAP MBC", "Banking", "Treasury"],
    relatedIndustries: ["financial-services", "retail", "telecommunications"],
    relatedSolutions: ["sap-mbc"],
    readTimeMinutes: 5,
    featured: false,
  },
  // Financial Supply Chain (3)
  {
    slug: "credit-management-explained",
    title: "Credit Management Explained",
    titleKo: "신용 관리 설명",
    titleJa: "クレジット管理の解説",
    excerpt: "Effective credit management balances revenue growth with risk mitigation. SAP FSCM's credit management module provides real-time credit scoring and automated limit management.",
    category: "Financial Supply Chain",
    tags: ["SAP FSCM", "Credit Management", "Risk"],
    relatedIndustries: ["financial-services", "retail", "telecommunications"],
    relatedSolutions: ["sap-fscm"],
    readTimeMinutes: 6,
    featured: false,
  },
  {
    slug: "collections-management",
    title: "Collections Management",
    titleKo: "수금 관리",
    titleJa: "回収管理",
    excerpt: "Intelligent collections management prioritizes overdue accounts, automates dunning processes, and reduces days sales outstanding (DSO) across your customer portfolio.",
    category: "Financial Supply Chain",
    tags: ["SAP FSCM", "Collections", "DSO"],
    relatedIndustries: ["financial-services", "retail", "telecommunications"],
    relatedSolutions: ["sap-fscm"],
    readTimeMinutes: 5,
    featured: false,
  },
  {
    slug: "dispute-management",
    title: "Dispute Management",
    titleKo: "분쟁 관리",
    titleJa: "紛争管理",
    excerpt: "Streamlining dispute resolution accelerates cash collection and improves customer relationships. SAP FSCM's dispute management provides end-to-end case management.",
    category: "Financial Supply Chain",
    tags: ["SAP FSCM", "Dispute Management", "Collections"],
    relatedIndustries: ["retail", "financial-services", "telecommunications"],
    relatedSolutions: ["sap-fscm"],
    readTimeMinutes: 5,
    featured: false,
  },
  // Billing & Revenue (2)
  {
    slug: "what-is-brim",
    title: "What is BRIM?",
    titleKo: "BRIM이란 무엇인가?",
    titleJa: "BRIMとは何か？",
    excerpt: "SAP Billing and Revenue Innovation Management (BRIM) is a comprehensive platform for managing complex billing scenarios including subscriptions, usage-based pricing, and hybrid models.",
    category: "Billing & Revenue",
    tags: ["SAP BRIM", "Billing", "Revenue Management"],
    relatedIndustries: ["telecommunications", "utilities", "financial-services"],
    relatedSolutions: ["sap-brim"],
    readTimeMinutes: 7,
    featured: false,
  },
  {
    slug: "revenue-recognition-explained",
    title: "Revenue Recognition Explained",
    titleKo: "수익 인식 설명",
    titleJa: "収益認識の解説",
    excerpt: "ASC 606 and IFRS 15 have fundamentally changed how organizations recognize revenue. Understanding these standards is critical for accurate financial reporting.",
    category: "Billing & Revenue",
    tags: ["Revenue Recognition", "IFRS 15", "ASC 606", "SAP BRIM"],
    relatedIndustries: ["telecommunications", "financial-services", "retail"],
    relatedSolutions: ["sap-brim"],
    readTimeMinutes: 8,
    featured: false,
  },
  // Risk & Compliance (2)
  {
    slug: "what-is-grc",
    title: "What is GRC?",
    titleKo: "GRC란 무엇인가?",
    titleJa: "GRCとは何か？",
    excerpt: "Governance, Risk, and Compliance (GRC) is a framework for managing an organization's overall governance, enterprise risk management, and regulatory compliance.",
    category: "Risk & Compliance",
    tags: ["SAP GRC", "Governance", "Risk", "Compliance"],
    relatedIndustries: ["financial-services", "pharmaceuticals", "energy"],
    relatedSolutions: ["sap-grc"],
    readTimeMinutes: 7,
    featured: false,
  },
  {
    slug: "audit-automation",
    title: "Audit Automation",
    titleKo: "감사 자동화",
    titleJa: "監査の自動化",
    excerpt: "Automating audit processes reduces the time and cost of compliance while improving the quality and consistency of audit evidence.",
    category: "Risk & Compliance",
    tags: ["Audit", "Automation", "SAP GRC", "Compliance"],
    relatedIndustries: ["financial-services", "pharmaceuticals", "utilities"],
    relatedSolutions: ["sap-grc"],
    readTimeMinutes: 6,
    featured: false,
  },
  // Lease Management (2)
  {
    slug: "ifrs-16-explained",
    title: "IFRS 16 Explained",
    titleKo: "IFRS 16 설명",
    titleJa: "IFRS 16の解説",
    excerpt: "IFRS 16 requires lessees to recognize most leases on the balance sheet, fundamentally changing how lease obligations are reported in financial statements.",
    category: "Lease Management",
    tags: ["IFRS 16", "Lease Management", "SAP RE-FX"],
    relatedIndustries: ["real-estate", "retail", "energy"],
    relatedSolutions: ["sap-re-fx"],
    readTimeMinutes: 8,
    featured: false,
  },
  {
    slug: "lease-management-solutions",
    title: "Lease Management Solutions",
    titleKo: "리스 관리 솔루션",
    titleJa: "リース管理ソリューション",
    excerpt: "Managing a large portfolio of leases requires specialized software that can handle complex calculations, automate journal entries, and ensure IFRS 16 compliance.",
    category: "Lease Management",
    tags: ["Lease Management", "SAP RE-FX", "IFRS 16"],
    relatedIndustries: ["real-estate", "retail", "utilities"],
    relatedSolutions: ["sap-re-fx"],
    readTimeMinutes: 6,
    featured: false,
  },
  // Finance Transformation (10)
  {
    slug: "why-cfos-invest-in-finance-transformation",
    title: "Why CFOs Invest in Finance Transformation",
    titleKo: "CFO가 재무 혁신에 투자하는 이유",
    titleJa: "CFOが財務変革に投資する理由",
    excerpt: "Finance transformation is no longer optional. CFOs are investing in technology to reduce costs, improve decision-making speed, and position finance as a strategic business partner.",
    excerptKo: "재무 혁신은 이제 선택이 아닌 필수입니다. CFO들은 비용 절감, 의사결정 속도 향상, 재무 부서의 전략적 파트너로의 전환을 위해 기술에 투자하고 있습니다.",
    excerptJa: "財務変革はもはや選択肢ではありません。CFOはコスト削減、意思決定スピードの向上、財務部門を戦略的ビジネスパートナーとして位置づけるために技術に投資しています。",
    category: "Finance Transformation",
    tags: ["Finance Transformation", "CFO", "Strategy"],
    relatedIndustries: ["financial-services", "retail", "pharmaceuticals"],
    relatedSolutions: ["sap-afc", "sap-analytics-cloud"],
    readTimeMinutes: 7,
    featured: true,
  },
  {
    slug: "evolution-of-finance-teams",
    title: "Evolution of Finance Teams",
    titleKo: "재무 팀의 진화",
    titleJa: "財務チームの進化",
    excerpt: "Finance teams are evolving from transaction processors to strategic advisors. Technology is enabling this shift by automating routine tasks and providing real-time insights.",
    category: "Finance Transformation",
    tags: ["Finance Transformation", "Future of Finance", "Strategy"],
    relatedIndustries: ["financial-services", "retail", "telecommunications"],
    relatedSolutions: ["sap-analytics-cloud"],
    readTimeMinutes: 6,
    featured: false,
  },
  {
    slug: "why-month-end-close-is-inefficient",
    title: "Why Month-End Close is Inefficient",
    titleKo: "월말 결산이 비효율적인 이유",
    titleJa: "月次決算が非効率な理由",
    excerpt: "The traditional month-end close process is plagued by manual tasks, siloed data, and poor visibility. Understanding the root causes is the first step to improvement.",
    category: "Finance Transformation",
    tags: ["Financial Close", "Finance Transformation", "Automation"],
    relatedIndustries: ["financial-services", "retail", "automotive"],
    relatedSolutions: ["sap-afc", "blackline"],
    readTimeMinutes: 7,
    featured: false,
  },
  {
    slug: "automation-in-finance",
    title: "Automation in Finance",
    titleKo: "재무의 자동화",
    titleJa: "財務における自動化",
    excerpt: "Robotic process automation (RPA), AI, and intelligent ERP platforms are transforming finance operations, reducing manual effort by up to 80% in leading organizations.",
    category: "Finance Transformation",
    tags: ["Automation", "RPA", "AI", "Finance Transformation"],
    relatedIndustries: ["financial-services", "retail", "pharmaceuticals"],
    relatedSolutions: ["sap-afc", "blackline", "sap-analytics-cloud"],
    readTimeMinutes: 8,
    featured: false,
  },
  {
    slug: "real-time-finance-reporting",
    title: "Real-Time Finance Reporting",
    titleKo: "실시간 재무 보고",
    titleJa: "リアルタイム財務レポーティング",
    excerpt: "Real-time financial reporting enables faster decision-making, reduces the close cycle, and provides stakeholders with up-to-date insights into business performance.",
    category: "Finance Transformation",
    tags: ["Real-Time Reporting", "Finance Transformation", "Analytics"],
    relatedIndustries: ["financial-services", "retail", "energy"],
    relatedSolutions: ["sap-analytics-cloud", "sap-group-reporting"],
    readTimeMinutes: 6,
    featured: false,
  },
  {
    slug: "erp-vs-finance-transformation",
    title: "ERP vs Finance Transformation",
    titleKo: "ERP vs 재무 혁신",
    titleJa: "ERPvs財務変革",
    excerpt: "ERP implementation and finance transformation are related but distinct initiatives. Understanding the difference is critical for setting realistic expectations and measuring success.",
    category: "Finance Transformation",
    tags: ["ERP", "Finance Transformation", "SAP", "Oracle"],
    relatedIndustries: ["financial-services", "automotive", "pharmaceuticals"],
    relatedSolutions: ["sap-afc", "oracle-fccs"],
    readTimeMinutes: 7,
    featured: false,
  },
  {
    slug: "standardizing-global-finance",
    title: "Standardizing Global Finance",
    titleKo: "글로벌 재무 표준화",
    titleJa: "グローバル財務の標準化",
    excerpt: "Global organizations face significant challenges in standardizing finance processes across regions with different regulations, currencies, and business practices.",
    category: "Finance Transformation",
    tags: ["Global Finance", "Standardization", "Finance Transformation"],
    relatedIndustries: ["automotive", "pharmaceuticals", "telecommunications"],
    relatedSolutions: ["sap-group-reporting", "sap-drc"],
    readTimeMinutes: 7,
    featured: false,
  },
  {
    slug: "rise-of-saas-finance-systems",
    title: "Rise of SaaS Finance Systems",
    titleKo: "SaaS 재무 시스템의 부상",
    titleJa: "SaaS財務システムの台頭",
    excerpt: "Cloud-based SaaS finance systems are displacing on-premise ERP for many finance functions, offering faster implementation, lower TCO, and continuous innovation.",
    category: "Finance Transformation",
    tags: ["SaaS", "Cloud", "Finance Transformation"],
    relatedIndustries: ["financial-services", "retail", "telecommunications"],
    relatedSolutions: ["oracle-fccs", "oracle-arcs", "sap-analytics-cloud"],
    readTimeMinutes: 6,
    featured: false,
  },
  {
    slug: "importance-of-integration",
    title: "Importance of Integration",
    titleKo: "통합의 중요성",
    titleJa: "統合の重要性",
    excerpt: "Finance system integration is the foundation of data quality and process efficiency. Disconnected systems create reconciliation overhead, data errors, and reporting delays.",
    category: "Finance Transformation",
    tags: ["Integration", "Finance Transformation", "Data Quality"],
    relatedIndustries: ["financial-services", "retail", "automotive"],
    relatedSolutions: ["sap-afc", "blackline", "sap-mbc"],
    readTimeMinutes: 6,
    featured: false,
  },
  {
    slug: "finance-as-competitive-advantage",
    title: "Finance as Competitive Advantage",
    titleKo: "경쟁 우위로서의 재무",
    titleJa: "競争優位としての財務",
    excerpt: "Leading organizations are using finance transformation to create competitive advantage through faster decision-making, better capital allocation, and superior risk management.",
    category: "Finance Transformation",
    tags: ["Finance Transformation", "Strategy", "Competitive Advantage"],
    relatedIndustries: ["financial-services", "retail", "pharmaceuticals"],
    relatedSolutions: ["sap-analytics-cloud", "sap-afc"],
    readTimeMinutes: 7,
    featured: false,
  },
  // Industry Trends (8)
  {
    slug: "global-tax-regulation-changes",
    title: "Global Tax Regulation Changes",
    titleKo: "글로벌 세금 규정 변화",
    titleJa: "グローバル税規制の変化",
    excerpt: "Tax regulations are changing rapidly worldwide, with new e-invoicing mandates, digital reporting requirements, and BEPS implementation creating compliance challenges.",
    category: "Industry Trends",
    tags: ["Tax Regulation", "Compliance", "Global"],
    relatedIndustries: ["financial-services", "retail", "oil-and-gas"],
    relatedSolutions: ["sap-drc"],
    readTimeMinutes: 8,
    featured: false,
  },
  {
    slug: "inflation-and-interest-rate-impact",
    title: "Inflation & Interest Rate Impact",
    titleKo: "인플레이션 및 금리 영향",
    titleJa: "インフレと金利の影響",
    excerpt: "Rising inflation and interest rates are reshaping treasury management, capital allocation, and financial planning strategies for CFOs across all industries.",
    category: "Industry Trends",
    tags: ["Treasury", "Inflation", "Interest Rates", "CFO"],
    relatedIndustries: ["financial-services", "real-estate", "energy"],
    relatedSolutions: ["sap-trm", "sap-cash-management"],
    readTimeMinutes: 7,
    featured: false,
  },
  {
    slug: "supply-chain-disruptions",
    title: "Supply Chain Disruptions",
    titleKo: "공급망 혼란",
    titleJa: "サプライチェーンの混乱",
    excerpt: "Global supply chain disruptions have exposed financial vulnerabilities in many organizations, highlighting the need for better financial supply chain management and scenario planning.",
    category: "Industry Trends",
    tags: ["Supply Chain", "Financial Supply Chain", "Risk"],
    relatedIndustries: ["automotive", "semiconductors", "pharmaceuticals"],
    relatedSolutions: ["sap-fscm", "sap-analytics-cloud"],
    readTimeMinutes: 7,
    featured: false,
  },
  {
    slug: "financial-transparency-trends",
    title: "Financial Transparency Trends",
    titleKo: "재무 투명성 트렌드",
    titleJa: "財務透明性のトレンド",
    excerpt: "Stakeholders are demanding greater financial transparency from organizations, driving investment in real-time reporting, ESG disclosure, and audit-ready processes.",
    category: "Industry Trends",
    tags: ["Transparency", "Reporting", "ESG"],
    relatedIndustries: ["financial-services", "energy", "pharmaceuticals"],
    relatedSolutions: ["sap-group-reporting", "sap-analytics-cloud"],
    readTimeMinutes: 6,
    featured: false,
  },
  {
    slug: "real-time-government-reporting",
    title: "Real-Time Government Reporting",
    titleKo: "실시간 정부 보고",
    titleJa: "リアルタイム政府報告",
    excerpt: "Governments are increasingly requiring real-time or near-real-time financial reporting from businesses, fundamentally changing the compliance landscape.",
    category: "Industry Trends",
    tags: ["Government Reporting", "Compliance", "E-Invoicing"],
    relatedIndustries: ["retail", "financial-services", "oil-and-gas"],
    relatedSolutions: ["sap-drc"],
    readTimeMinutes: 7,
    featured: false,
  },
  {
    slug: "esg-reporting-impact",
    title: "ESG Reporting Impact",
    titleKo: "ESG 보고의 영향",
    titleJa: "ESGレポーティングの影響",
    excerpt: "Environmental, Social, and Governance (ESG) reporting requirements are expanding globally, creating new demands on finance teams for data collection, validation, and disclosure.",
    category: "Industry Trends",
    tags: ["ESG", "Reporting", "Sustainability"],
    relatedIndustries: ["energy", "renewable-energy", "financial-services"],
    relatedSolutions: ["sap-group-reporting", "sap-analytics-cloud"],
    readTimeMinutes: 8,
    featured: false,
  },
  {
    slug: "cross-border-complexity",
    title: "Cross-Border Complexity",
    titleKo: "국경 간 복잡성",
    titleJa: "国境を越えた複雑性",
    excerpt: "Managing finance across multiple jurisdictions involves navigating different tax regimes, currencies, regulations, and reporting standards — a challenge that technology can help solve.",
    category: "Industry Trends",
    tags: ["Cross-Border", "Global Finance", "Tax Compliance"],
    relatedIndustries: ["financial-services", "pharmaceuticals", "oil-and-gas"],
    relatedSolutions: ["sap-drc", "sap-group-reporting"],
    readTimeMinutes: 7,
    featured: false,
  },
  {
    slug: "data-accuracy-importance",
    title: "Data Accuracy Importance",
    titleKo: "데이터 정확성의 중요성",
    titleJa: "データ精度の重要性",
    excerpt: "Financial data accuracy is the foundation of reliable reporting, effective decision-making, and regulatory compliance. Poor data quality costs organizations millions annually.",
    category: "Industry Trends",
    tags: ["Data Quality", "Finance", "Reporting"],
    relatedIndustries: ["financial-services", "retail", "pharmaceuticals"],
    relatedSolutions: ["blackline", "oracle-arcs"],
    readTimeMinutes: 6,
    featured: false,
  },
  // Technology (3)
  {
    slug: "predictive-finance",
    title: "Predictive Finance",
    titleKo: "예측 재무",
    titleJa: "予測財務",
    excerpt: "Predictive finance uses machine learning and advanced analytics to forecast financial outcomes with greater accuracy, enabling proactive decision-making.",
    category: "Technology",
    tags: ["Predictive Analytics", "AI", "Finance"],
    relatedIndustries: ["financial-services", "retail", "telecommunications"],
    relatedSolutions: ["sap-analytics-cloud"],
    readTimeMinutes: 7,
    featured: false,
  },
  {
    slug: "ai-in-finance",
    title: "AI in Finance",
    titleKo: "재무의 AI",
    titleJa: "財務におけるAI",
    excerpt: "Artificial intelligence is transforming finance functions from transaction processing to strategic analysis, with applications in anomaly detection, forecasting, and process automation.",
    category: "Technology",
    tags: ["AI", "Machine Learning", "Finance Transformation"],
    relatedIndustries: ["financial-services", "retail", "pharmaceuticals"],
    relatedSolutions: ["sap-analytics-cloud", "sap-afc"],
    readTimeMinutes: 8,
    featured: true,
  },
  {
    slug: "modern-finance-stack-in-2026",
    title: "Modern Finance Stack in 2026",
    titleKo: "2026년 현대 재무 스택",
    titleJa: "2026年のモダン財務スタック",
    excerpt: "The modern finance technology stack in 2026 combines core ERP with specialized best-of-breed solutions for close, planning, treasury, and compliance.",
    category: "Technology",
    tags: ["Finance Stack", "Technology", "ERP", "Best-of-Breed"],
    relatedIndustries: ["financial-services", "retail", "automotive"],
    relatedSolutions: ["sap-afc", "blackline", "sap-analytics-cloud"],
    readTimeMinutes: 9,
    featured: false,
  },
  // Industry Focus (12)
  {
    slug: "automotive-finance-transformation",
    title: "Automotive Finance Transformation",
    titleKo: "자동차 재무 혁신",
    titleJa: "自動車業界の財務変革",
    excerpt: "The automotive industry is undergoing unprecedented transformation. Finance teams must adapt to EV transitions, supply chain complexity, and new revenue models.",
    category: "Industry Focus",
    tags: ["Automotive", "Finance Transformation", "EV"],
    relatedIndustries: ["automotive"],
    relatedSolutions: ["sap-afc", "sap-analytics-cloud", "sap-fscm"],
    readTimeMinutes: 8,
    featured: false,
  },
  {
    slug: "semiconductor-finance-complexity",
    title: "Semiconductor Finance Complexity",
    titleKo: "반도체 재무 복잡성",
    titleJa: "半導体財務の複雑性",
    excerpt: "Semiconductor companies face unique financial challenges including long R&D cycles, complex IP licensing, and volatile demand patterns that require sophisticated financial management.",
    category: "Industry Focus",
    tags: ["Semiconductors", "Finance", "R&D"],
    relatedIndustries: ["semiconductors"],
    relatedSolutions: ["sap-analytics-cloud", "sap-afc", "sap-trm"],
    readTimeMinutes: 7,
    featured: false,
  },
  {
    slug: "energy-sector-finance",
    title: "Energy Sector Finance",
    titleKo: "에너지 부문 재무",
    titleJa: "エネルギーセクターの財務",
    excerpt: "Energy companies face complex financial challenges including commodity price volatility, capital-intensive projects, and evolving regulatory requirements.",
    category: "Industry Focus",
    tags: ["Energy", "Finance", "Commodity Risk"],
    relatedIndustries: ["energy", "oil-and-gas", "renewable-energy"],
    relatedSolutions: ["sap-trm", "sap-analytics-cloud", "sap-grc"],
    readTimeMinutes: 7,
    featured: false,
  },
  {
    slug: "telecom-finance-challenges",
    title: "Telecom Finance Challenges",
    titleKo: "통신 재무 과제",
    titleJa: "通信業界の財務課題",
    excerpt: "Telecommunications companies manage complex billing arrangements, network infrastructure investments, and regulatory compliance across multiple markets.",
    category: "Industry Focus",
    tags: ["Telecommunications", "Finance", "Billing"],
    relatedIndustries: ["telecommunications"],
    relatedSolutions: ["sap-brim", "sap-analytics-cloud", "sap-fscm"],
    readTimeMinutes: 7,
    featured: false,
  },
  {
    slug: "saas-finance-models",
    title: "SaaS Finance Models",
    titleKo: "SaaS 재무 모델",
    titleJa: "SaaS財務モデル",
    excerpt: "SaaS companies require specialized financial management for subscription revenue recognition, customer lifetime value tracking, and recurring billing operations.",
    category: "Industry Focus",
    tags: ["SaaS", "Finance", "Revenue Recognition", "Billing"],
    relatedIndustries: ["financial-services", "telecommunications"],
    relatedSolutions: ["sap-brim", "oracle-fccs"],
    readTimeMinutes: 6,
    featured: false,
  },
  {
    slug: "e-commerce-finance",
    title: "E-commerce Finance",
    titleKo: "이커머스 재무",
    titleJa: "Eコマース財務",
    excerpt: "E-commerce finance teams manage high transaction volumes, complex tax obligations across jurisdictions, and real-time inventory valuation challenges.",
    category: "Industry Focus",
    tags: ["E-commerce", "Finance", "Tax Compliance"],
    relatedIndustries: ["retail"],
    relatedSolutions: ["sap-drc", "sap-brim", "sap-fscm"],
    readTimeMinutes: 6,
    featured: false,
  },
  {
    slug: "pharma-finance",
    title: "Pharma Finance",
    titleKo: "제약 재무",
    titleJa: "製薬業界の財務",
    excerpt: "Pharmaceutical companies face unique financial challenges including long product development cycles, complex royalty arrangements, and stringent regulatory reporting requirements.",
    category: "Industry Focus",
    tags: ["Pharmaceuticals", "Finance", "R&D", "Compliance"],
    relatedIndustries: ["pharmaceuticals"],
    relatedSolutions: ["sap-afc", "sap-grc", "sap-analytics-cloud"],
    readTimeMinutes: 7,
    featured: false,
  },
  {
    slug: "logistics-finance",
    title: "Logistics Finance",
    titleKo: "물류 재무",
    titleJa: "物流財務",
    excerpt: "Logistics and supply chain companies require sophisticated financial management for asset-heavy operations, complex customer contracts, and cross-border transactions.",
    category: "Industry Focus",
    tags: ["Logistics", "Finance", "Supply Chain"],
    relatedIndustries: ["automotive", "retail"],
    relatedSolutions: ["sap-fscm", "sap-analytics-cloud"],
    readTimeMinutes: 6,
    featured: false,
  },
  {
    slug: "real-estate-finance",
    title: "Real Estate Finance",
    titleKo: "부동산 재무",
    titleJa: "不動産財務",
    excerpt: "Real estate companies manage complex lease portfolios, property valuations, and investment structures that require specialized financial management capabilities.",
    category: "Industry Focus",
    tags: ["Real Estate", "Finance", "Lease Management", "IFRS 16"],
    relatedIndustries: ["real-estate"],
    relatedSolutions: ["sap-re-fx", "sap-analytics-cloud"],
    readTimeMinutes: 7,
    featured: false,
  },
  {
    slug: "best-of-breed-vs-erp",
    title: "Best-of-Breed vs ERP",
    titleKo: "최고의 솔루션 vs ERP",
    titleJa: "ベストオブブリードvsERP",
    excerpt: "The debate between best-of-breed financial applications and integrated ERP suites continues to evolve as cloud technology reduces integration complexity.",
    category: "Technology",
    tags: ["Best-of-Breed", "ERP", "Technology Strategy"],
    relatedIndustries: ["financial-services", "retail", "pharmaceuticals"],
    relatedSolutions: ["blackline", "sap-afc", "oracle-fccs"],
    readTimeMinutes: 8,
    featured: false,
  },
  {
    slug: "sap-vs-oracle-finance",
    title: "SAP vs Oracle Finance",
    titleKo: "SAP vs Oracle 재무",
    titleJa: "SAPvsOracle財務",
    excerpt: "SAP and Oracle are the two dominant vendors in enterprise financial management. This analysis compares their strengths, weaknesses, and ideal use cases.",
    category: "Technology",
    tags: ["SAP", "Oracle", "ERP", "Technology"],
    relatedIndustries: ["financial-services", "automotive", "pharmaceuticals"],
    relatedSolutions: ["sap-afc", "oracle-fccs", "sap-analytics-cloud", "oracle-pbcs"],
    readTimeMinutes: 10,
    featured: false,
  },
  {
    slug: "why-companies-use-both-sap-and-oracle",
    title: "Why Companies Use Both SAP & Oracle",
    titleKo: "기업이 SAP와 Oracle을 모두 사용하는 이유",
    titleJa: "企業がSAPとOracleの両方を使用する理由",
    excerpt: "Many large enterprises run both SAP and Oracle systems simultaneously. Understanding why — and how to manage this complexity — is critical for finance technology leaders.",
    category: "Technology",
    tags: ["SAP", "Oracle", "ERP", "Integration"],
    relatedIndustries: ["financial-services", "pharmaceuticals", "automotive"],
    relatedSolutions: ["sap-afc", "oracle-fccs", "sap-group-reporting"],
    readTimeMinutes: 8,
    featured: false,
  },
  {
    slug: "future-of-the-cfo",
    title: "Future of the CFO",
    titleKo: "CFO의 미래",
    titleJa: "CFOの未来",
    excerpt: "The CFO role is evolving from financial steward to strategic business partner. Technology, data, and sustainability are reshaping the skills and priorities of tomorrow's CFO.",
    category: "Finance Transformation",
    tags: ["CFO", "Future of Finance", "Strategy"],
    relatedIndustries: ["financial-services", "retail", "pharmaceuticals"],
    relatedSolutions: ["sap-analytics-cloud"],
    readTimeMinutes: 7,
    featured: false,
  }
      ];
